// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0FpIkd310m58KguS1VFjA95lTaGQwAiQ',
    appId: '1:155322514449:web:83e30dcf35e0120ba685b0',
    messagingSenderId: '155322514449',
    projectId: 'ligue1fantasy-a3d52',
    authDomain: 'ligue1fantasy-a3d52.firebaseapp.com',
    storageBucket: 'ligue1fantasy-a3d52.appspot.com',
    measurementId: 'G-1Q40B9E7K1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdQg7Ps3kN4soV-rVeudtBOfViBoc6o3A',
    appId: '1:155322514449:android:e78cc2120d1672eaa685b0',
    messagingSenderId: '155322514449',
    projectId: 'ligue1fantasy-a3d52',
    storageBucket: 'ligue1fantasy-a3d52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqHdTovn5WzGXNcsZnEX0NCjPA2qSMAo0',
    appId: '1:155322514449:ios:2649db6497749fa7a685b0',
    messagingSenderId: '155322514449',
    projectId: 'ligue1fantasy-a3d52',
    storageBucket: 'ligue1fantasy-a3d52.appspot.com',
    iosClientId: '155322514449-nnifi0g8mehulsebgt02jv0hs4uuo6kv.apps.googleusercontent.com',
    iosBundleId: 'com.example.fantasyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqHdTovn5WzGXNcsZnEX0NCjPA2qSMAo0',
    appId: '1:155322514449:ios:2649db6497749fa7a685b0',
    messagingSenderId: '155322514449',
    projectId: 'ligue1fantasy-a3d52',
    storageBucket: 'ligue1fantasy-a3d52.appspot.com',
    iosClientId: '155322514449-nnifi0g8mehulsebgt02jv0hs4uuo6kv.apps.googleusercontent.com',
    iosBundleId: 'com.example.fantasyapp',
  );
}
